<?php
/**
 * EntitiesApi
 * PHP version 5
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa Private API
 *
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TransferZero\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use TransferZero\ApiException;
use TransferZero\Configuration;
use TransferZero\HeaderSelector;
use TransferZero\ObjectSerializer;

/**
 * EntitiesApi Class Doc Comment
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EntitiesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

     /**
     * @var string
     */
    const DIGEST = 'SHA512';

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Use the Authorization Signature in the request headers to validate the payload
     *
     * @param $url The full url including any query strings
     * @param $body The string received through the webhook callback url
     * @param $headers The request headers received by the webhook endpoint
     *
     * @return boolean
     */
    public function validateWebhookRequest($url, $body, $headers) {
        $requestNonce = $headers["Authorization-Nonce"];
        $requestSignature = $headers["Authorization-Signature"];
        $requestkey = $headers["Authorization-Key"];

        if (empty($requestNonce) || empty($requestSignature) || ($requestkey != $this->config->getApiKey())) {
            return false;
        }

        $headerSignature = $this->signRequest([
            $requestNonce,
            'POST',
            $url,
            $this->digestHash($body)
        ]);

        return ($headerSignature == $requestSignature);
    }

    /**
     * Operation getEntities
     *
     * Listing entities
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/summary?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     * @param  string[] $ids Returns entities of specified entity(e.g Sender) id(s). This allows the fetching of entities for multiple e.g. senders  Example: &#x60;/risk_assessment/entities/sender?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TransferZero\Model\EntityListResponse
     */
    public function getEntities($associative_array)
    {
        list($response) = $this->getEntitiesWithHttpInfo($associative_array);
        return $response;
    }

    /**
     * Operation getEntitiesWithHttpInfo
     *
     * Listing entities
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/summary?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     * @param  string[] $ids Returns entities of specified entity(e.g Sender) id(s). This allows the fetching of entities for multiple e.g. senders  Example: &#x60;/risk_assessment/entities/sender?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TransferZero\Model\EntityListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEntitiesWithHttpInfo($associative_array)
    {
        $returnType = '\TransferZero\Model\EntityListResponse';
        $request = $this->getEntitiesRequest($associative_array);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode == 422) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody(),
                    true
                );
            } elseif ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\EntityListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getEntitiesAsync
     *
     * Listing entities
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/summary?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     * @param  string[] $ids Returns entities of specified entity(e.g Sender) id(s). This allows the fetching of entities for multiple e.g. senders  Example: &#x60;/risk_assessment/entities/sender?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEntitiesAsync($associative_array)
    {
        return $this->getEntitiesAsyncWithHttpInfo($associative_array)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEntitiesAsyncWithHttpInfo
     *
     * Listing entities
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/summary?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     * @param  string[] $ids Returns entities of specified entity(e.g Sender) id(s). This allows the fetching of entities for multiple e.g. senders  Example: &#x60;/risk_assessment/entities/sender?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEntitiesAsyncWithHttpInfo($associative_array)
    {
        $returnType = '\TransferZero\Model\EntityListResponse';
        $request = $this->getEntitiesRequest($associative_array);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEntities'
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/summary?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     * @param  string[] $ids Returns entities of specified entity(e.g Sender) id(s). This allows the fetching of entities for multiple e.g. senders  Example: &#x60;/risk_assessment/entities/sender?ids[]&#x3D;bf9ff782-e182-45ac-abea-5bce83ad6670&amp;ids[]&#x3D;344fb668-196d-43db-9d94-b34b7e6c7e0b&#x60; (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getEntitiesRequest($associative_array)
    {
        // unbox the parameters from the associative array
        $entity_type = array_key_exists('entity_type', $associative_array) ? $associative_array['entity_type'] : null;
        $ids = array_key_exists('ids', $associative_array) ? $associative_array['ids'] : null;

        // verify the required parameter 'entity_type' is set
        if ($entity_type === null || (is_array($entity_type) && count($entity_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_type when calling getEntities'
            );
        }
        // verify the required parameter 'ids' is set
        if ($ids === null || (is_array($ids) && count($ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ids when calling getEntities'
            );
        }

        $resourcePath = '/risk_assessment/entities/{Entity Type}/summary';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($ids)) {
            $ids = ObjectSerializer::serializeCollection($ids, 'multi', true);
        }
        if ($ids !== null) {
            $queryParams['ids'] = ObjectSerializer::toQueryValue($ids);
        }

        // path params
        if ($entity_type !== null) {
            $resourcePath = str_replace(
                '{' . 'Entity Type' . '}',
                ObjectSerializer::toPathValue($entity_type),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $query = \GuzzleHttp\Psr7\build_query($queryParams);

        $httpMethod = 'GET';
        $urlWithParams = $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : '');

        $requestNonce = $this->guidv4Nonce();
        $requestSignature = $this->signRequest([
            $requestNonce,
            strtoupper($httpMethod),
            $urlWithParams,
            $this->digestHash($httpBody)
        ]);

        $headers['Authorization-Nonce'] = $requestNonce;
        $headers['Authorization-Signature'] = $requestSignature;
        $headers['Authorization-Key'] = $this->config->getApiKey();

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        return new Request(
            'GET',
            $urlWithParams,
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEntitiesByParams
     *
     * Listing entities by params (rating and/or state)
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to retrieve.  Example: &#x60;/risk_assessment/entities/sender/search?rating&#x3D;extremely_high&amp;state&#x3D;complete&#x60; (required)
     * @param  string $rating Returns a list of entities scoped by the Entity rating (rating param can be one of &#39;extremely_high&#39;, &#39;high_risk&#39;, &#39;medium_risk&#39; or &#39;low_risk&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?rating&#x3D;extremely_high&#x60; (optional)
     * @param  string $state Returns a list of entities scoped by the Entity state (state param can be one of &#39;complete&#39; or &#39;incomplete&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?state&#x3D;complete&#x60; (optional)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TransferZero\Model\EntityListResponse
     */
    public function getEntitiesByParams($associative_array)
    {
        list($response) = $this->getEntitiesByParamsWithHttpInfo($associative_array);
        return $response;
    }

    /**
     * Operation getEntitiesByParamsWithHttpInfo
     *
     * Listing entities by params (rating and/or state)
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to retrieve.  Example: &#x60;/risk_assessment/entities/sender/search?rating&#x3D;extremely_high&amp;state&#x3D;complete&#x60; (required)
     * @param  string $rating Returns a list of entities scoped by the Entity rating (rating param can be one of &#39;extremely_high&#39;, &#39;high_risk&#39;, &#39;medium_risk&#39; or &#39;low_risk&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?rating&#x3D;extremely_high&#x60; (optional)
     * @param  string $state Returns a list of entities scoped by the Entity state (state param can be one of &#39;complete&#39; or &#39;incomplete&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?state&#x3D;complete&#x60; (optional)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TransferZero\Model\EntityListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEntitiesByParamsWithHttpInfo($associative_array)
    {
        $returnType = '\TransferZero\Model\EntityListResponse';
        $request = $this->getEntitiesByParamsRequest($associative_array);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode == 422) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody(),
                    true
                );
            } elseif ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\EntityListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getEntitiesByParamsAsync
     *
     * Listing entities by params (rating and/or state)
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to retrieve.  Example: &#x60;/risk_assessment/entities/sender/search?rating&#x3D;extremely_high&amp;state&#x3D;complete&#x60; (required)
     * @param  string $rating Returns a list of entities scoped by the Entity rating (rating param can be one of &#39;extremely_high&#39;, &#39;high_risk&#39;, &#39;medium_risk&#39; or &#39;low_risk&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?rating&#x3D;extremely_high&#x60; (optional)
     * @param  string $state Returns a list of entities scoped by the Entity state (state param can be one of &#39;complete&#39; or &#39;incomplete&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?state&#x3D;complete&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEntitiesByParamsAsync($associative_array)
    {
        return $this->getEntitiesByParamsAsyncWithHttpInfo($associative_array)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEntitiesByParamsAsyncWithHttpInfo
     *
     * Listing entities by params (rating and/or state)
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to retrieve.  Example: &#x60;/risk_assessment/entities/sender/search?rating&#x3D;extremely_high&amp;state&#x3D;complete&#x60; (required)
     * @param  string $rating Returns a list of entities scoped by the Entity rating (rating param can be one of &#39;extremely_high&#39;, &#39;high_risk&#39;, &#39;medium_risk&#39; or &#39;low_risk&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?rating&#x3D;extremely_high&#x60; (optional)
     * @param  string $state Returns a list of entities scoped by the Entity state (state param can be one of &#39;complete&#39; or &#39;incomplete&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?state&#x3D;complete&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEntitiesByParamsAsyncWithHttpInfo($associative_array)
    {
        $returnType = '\TransferZero\Model\EntityListResponse';
        $request = $this->getEntitiesByParamsRequest($associative_array);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEntitiesByParams'
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to retrieve.  Example: &#x60;/risk_assessment/entities/sender/search?rating&#x3D;extremely_high&amp;state&#x3D;complete&#x60; (required)
     * @param  string $rating Returns a list of entities scoped by the Entity rating (rating param can be one of &#39;extremely_high&#39;, &#39;high_risk&#39;, &#39;medium_risk&#39; or &#39;low_risk&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?rating&#x3D;extremely_high&#x60; (optional)
     * @param  string $state Returns a list of entities scoped by the Entity state (state param can be one of &#39;complete&#39; or &#39;incomplete&#39;)  Example: &#x60;/risk_assessment/entities/Sender::Business/search?state&#x3D;complete&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getEntitiesByParamsRequest($associative_array)
    {
        // unbox the parameters from the associative array
        $entity_type = array_key_exists('entity_type', $associative_array) ? $associative_array['entity_type'] : null;
        $rating = array_key_exists('rating', $associative_array) ? $associative_array['rating'] : null;
        $state = array_key_exists('state', $associative_array) ? $associative_array['state'] : null;

        // verify the required parameter 'entity_type' is set
        if ($entity_type === null || (is_array($entity_type) && count($entity_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_type when calling getEntitiesByParams'
            );
        }

        $resourcePath = '/risk_assessment/entities/{Entity Type}/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($rating !== null) {
            $queryParams['rating'] = ObjectSerializer::toQueryValue($rating);
        }
        // query params
        if ($state !== null) {
            $queryParams['state'] = ObjectSerializer::toQueryValue($state);
        }

        // path params
        if ($entity_type !== null) {
            $resourcePath = str_replace(
                '{' . 'Entity Type' . '}',
                ObjectSerializer::toPathValue($entity_type),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $query = \GuzzleHttp\Psr7\build_query($queryParams);

        $httpMethod = 'GET';
        $urlWithParams = $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : '');

        $requestNonce = $this->guidv4Nonce();
        $requestSignature = $this->signRequest([
            $requestNonce,
            strtoupper($httpMethod),
            $urlWithParams,
            $this->digestHash($httpBody)
        ]);

        $headers['Authorization-Nonce'] = $requestNonce;
        $headers['Authorization-Signature'] = $requestSignature;
        $headers['Authorization-Key'] = $this->config->getApiKey();

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        return new Request(
            'GET',
            $urlWithParams,
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEntity
     *
     * Fetching a entity
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TransferZero\Model\EntityCreateResponse
     */
    public function getEntity($associative_array)
    {
        list($response) = $this->getEntityWithHttpInfo($associative_array);
        return $response;
    }

    /**
     * Operation getEntityWithHttpInfo
     *
     * Fetching a entity
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TransferZero\Model\EntityCreateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEntityWithHttpInfo($associative_array)
    {
        $returnType = '\TransferZero\Model\EntityCreateResponse';
        $request = $this->getEntityRequest($associative_array);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode == 422) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody(),
                    true
                );
            } elseif ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\EntityCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getEntityAsync
     *
     * Fetching a entity
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEntityAsync($associative_array)
    {
        return $this->getEntityAsyncWithHttpInfo($associative_array)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEntityAsyncWithHttpInfo
     *
     * Fetching a entity
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEntityAsyncWithHttpInfo($associative_array)
    {
        $returnType = '\TransferZero\Model\EntityCreateResponse';
        $request = $this->getEntityRequest($associative_array);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEntity'
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getEntityRequest($associative_array)
    {
        // unbox the parameters from the associative array
        $entity_type = array_key_exists('entity_type', $associative_array) ? $associative_array['entity_type'] : null;
        $entity_id = array_key_exists('entity_id', $associative_array) ? $associative_array['entity_id'] : null;

        // verify the required parameter 'entity_type' is set
        if ($entity_type === null || (is_array($entity_type) && count($entity_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_type when calling getEntity'
            );
        }
        // verify the required parameter 'entity_id' is set
        if ($entity_id === null || (is_array($entity_id) && count($entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_id when calling getEntity'
            );
        }

        $resourcePath = '/risk_assessment/entities/{Entity Type}/{Entity ID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($entity_type !== null) {
            $resourcePath = str_replace(
                '{' . 'Entity Type' . '}',
                ObjectSerializer::toPathValue($entity_type),
                $resourcePath
            );
        }
        // path params
        if ($entity_id !== null) {
            $resourcePath = str_replace(
                '{' . 'Entity ID' . '}',
                ObjectSerializer::toPathValue($entity_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $query = \GuzzleHttp\Psr7\build_query($queryParams);

        $httpMethod = 'GET';
        $urlWithParams = $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : '');

        $requestNonce = $this->guidv4Nonce();
        $requestSignature = $this->signRequest([
            $requestNonce,
            strtoupper($httpMethod),
            $urlWithParams,
            $this->digestHash($httpBody)
        ]);

        $headers['Authorization-Nonce'] = $requestNonce;
        $headers['Authorization-Signature'] = $requestSignature;
        $headers['Authorization-Key'] = $this->config->getApiKey();

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        return new Request(
            'GET',
            $urlWithParams,
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchEntity
     *
     * Updating an entity
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  \TransferZero\Model\EntityUpdateRequest $entity_update_request entity_update_request (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TransferZero\Model\EntityUpdateResponse|\TransferZero\Model\EntityUpdateResponse
     */
    public function patchEntity($entity_type, $entity_id, $entity_update_request)
    {
        list($response) = $this->patchEntityWithHttpInfo($entity_type, $entity_id, $entity_update_request);
        return $response;
    }

    /**
     * Operation patchEntityWithHttpInfo
     *
     * Updating an entity
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  \TransferZero\Model\EntityUpdateRequest $entity_update_request (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TransferZero\Model\EntityUpdateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchEntityWithHttpInfo($entity_type, $entity_id, $entity_update_request)
    {
        $returnType = '\TransferZero\Model\EntityUpdateResponse';
        $request = $this->patchEntityRequest($entity_type, $entity_id, $entity_update_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode == 422) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody(),
                    true
                );
            } elseif ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\EntityUpdateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\EntityUpdateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation patchEntityAsync
     *
     * Updating an entity
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  \TransferZero\Model\EntityUpdateRequest $entity_update_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchEntityAsync($entity_type, $entity_id, $entity_update_request)
    {
        return $this->patchEntityAsyncWithHttpInfo($entity_type, $entity_id, $entity_update_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchEntityAsyncWithHttpInfo
     *
     * Updating an entity
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  \TransferZero\Model\EntityUpdateRequest $entity_update_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchEntityAsyncWithHttpInfo($entity_type, $entity_id, $entity_update_request)
    {
        $returnType = '\TransferZero\Model\EntityUpdateResponse';
        $request = $this->patchEntityRequest($entity_type, $entity_id, $entity_update_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchEntity'
     *
     * @param  string $entity_type Type of entities to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  string $entity_id ID of the entity to get.  Example: &#x60;/risk_assessment/entities/sender/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60; (required)
     * @param  \TransferZero\Model\EntityUpdateRequest $entity_update_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function patchEntityRequest($entity_type, $entity_id, $entity_update_request)
    {
        // verify the required parameter 'entity_type' is set
        if ($entity_type === null || (is_array($entity_type) && count($entity_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_type when calling patchEntity'
            );
        }
        // verify the required parameter 'entity_id' is set
        if ($entity_id === null || (is_array($entity_id) && count($entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_id when calling patchEntity'
            );
        }
        // verify the required parameter 'entity_update_request' is set
        if ($entity_update_request === null || (is_array($entity_update_request) && count($entity_update_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_update_request when calling patchEntity'
            );
        }

        $resourcePath = '/risk_assessment/entities/{Entity Type}/{Entity ID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($entity_type !== null) {
            $resourcePath = str_replace(
                '{' . 'Entity Type' . '}',
                ObjectSerializer::toPathValue($entity_type),
                $resourcePath
            );
        }
        // path params
        if ($entity_id !== null) {
            $resourcePath = str_replace(
                '{' . 'Entity ID' . '}',
                ObjectSerializer::toPathValue($entity_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($entity_update_request)) {
            $_tempBody = $entity_update_request;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $query = \GuzzleHttp\Psr7\build_query($queryParams);

        $httpMethod = 'PATCH';
        $urlWithParams = $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : '');

        $requestNonce = $this->guidv4Nonce();
        $requestSignature = $this->signRequest([
            $requestNonce,
            strtoupper($httpMethod),
            $urlWithParams,
            $this->digestHash($httpBody)
        ]);

        $headers['Authorization-Nonce'] = $requestNonce;
        $headers['Authorization-Signature'] = $requestSignature;
        $headers['Authorization-Key'] = $this->config->getApiKey();

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        return new Request(
            'PATCH',
            $urlWithParams,
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postEntity
     *
     * Creating an entity
     *
     * @param  string $entity_type Type of entity to create. (required)
     * @param  string $entity_id ID of entity type to create entity for.  Example: &#x60;/risk_assessment/entities/sender/e6f67a67-b2c2-4897-ad58-9fc3a9d8d991&#x60; (required)
     * @param  \TransferZero\Model\EntityCreateRequest $entity_create_request entity_create_request (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TransferZero\Model\EntityCreateResponse|\TransferZero\Model\EntityCreateResponse
     */
    public function postEntity($entity_type, $entity_id, $entity_create_request)
    {
        list($response) = $this->postEntityWithHttpInfo($entity_type, $entity_id, $entity_create_request);
        return $response;
    }

    /**
     * Operation postEntityWithHttpInfo
     *
     * Creating an entity
     *
     * @param  string $entity_type Type of entity to create. (required)
     * @param  string $entity_id ID of entity type to create entity for.  Example: &#x60;/risk_assessment/entities/sender/e6f67a67-b2c2-4897-ad58-9fc3a9d8d991&#x60; (required)
     * @param  \TransferZero\Model\EntityCreateRequest $entity_create_request (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TransferZero\Model\EntityCreateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postEntityWithHttpInfo($entity_type, $entity_id, $entity_create_request)
    {
        $returnType = '\TransferZero\Model\EntityCreateResponse';
        $request = $this->postEntityRequest($entity_type, $entity_id, $entity_create_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode == 422) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody(),
                    true
                );
            } elseif ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\EntityCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\EntityCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postEntityAsync
     *
     * Creating an entity
     *
     * @param  string $entity_type Type of entity to create. (required)
     * @param  string $entity_id ID of entity type to create entity for.  Example: &#x60;/risk_assessment/entities/sender/e6f67a67-b2c2-4897-ad58-9fc3a9d8d991&#x60; (required)
     * @param  \TransferZero\Model\EntityCreateRequest $entity_create_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postEntityAsync($entity_type, $entity_id, $entity_create_request)
    {
        return $this->postEntityAsyncWithHttpInfo($entity_type, $entity_id, $entity_create_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postEntityAsyncWithHttpInfo
     *
     * Creating an entity
     *
     * @param  string $entity_type Type of entity to create. (required)
     * @param  string $entity_id ID of entity type to create entity for.  Example: &#x60;/risk_assessment/entities/sender/e6f67a67-b2c2-4897-ad58-9fc3a9d8d991&#x60; (required)
     * @param  \TransferZero\Model\EntityCreateRequest $entity_create_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postEntityAsyncWithHttpInfo($entity_type, $entity_id, $entity_create_request)
    {
        $returnType = '\TransferZero\Model\EntityCreateResponse';
        $request = $this->postEntityRequest($entity_type, $entity_id, $entity_create_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postEntity'
     *
     * @param  string $entity_type Type of entity to create. (required)
     * @param  string $entity_id ID of entity type to create entity for.  Example: &#x60;/risk_assessment/entities/sender/e6f67a67-b2c2-4897-ad58-9fc3a9d8d991&#x60; (required)
     * @param  \TransferZero\Model\EntityCreateRequest $entity_create_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function postEntityRequest($entity_type, $entity_id, $entity_create_request)
    {
        // verify the required parameter 'entity_type' is set
        if ($entity_type === null || (is_array($entity_type) && count($entity_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_type when calling postEntity'
            );
        }
        // verify the required parameter 'entity_id' is set
        if ($entity_id === null || (is_array($entity_id) && count($entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_id when calling postEntity'
            );
        }
        // verify the required parameter 'entity_create_request' is set
        if ($entity_create_request === null || (is_array($entity_create_request) && count($entity_create_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $entity_create_request when calling postEntity'
            );
        }

        $resourcePath = '/risk_assessment/entities/{Entity Type}/{Entity ID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($entity_type !== null) {
            $resourcePath = str_replace(
                '{' . 'Entity Type' . '}',
                ObjectSerializer::toPathValue($entity_type),
                $resourcePath
            );
        }
        // path params
        if ($entity_id !== null) {
            $resourcePath = str_replace(
                '{' . 'Entity ID' . '}',
                ObjectSerializer::toPathValue($entity_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($entity_create_request)) {
            $_tempBody = $entity_create_request;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $query = \GuzzleHttp\Psr7\build_query($queryParams);

        $httpMethod = 'POST';
        $urlWithParams = $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : '');

        $requestNonce = $this->guidv4Nonce();
        $requestSignature = $this->signRequest([
            $requestNonce,
            strtoupper($httpMethod),
            $urlWithParams,
            $this->digestHash($httpBody)
        ]);

        $headers['Authorization-Nonce'] = $requestNonce;
        $headers['Authorization-Signature'] = $requestSignature;
        $headers['Authorization-Key'] = $this->config->getApiKey();

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        return new Request(
            'POST',
            $urlWithParams,
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        $options[RequestOptions::HTTP_ERRORS] = false;
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    /**
     * Parses and deserializes a response in string format.
     * Can be used to parse webhook responses that were already converted to strings
     *
     * @param object response the object we wish to parse
     * @param boolean returnType The type of the PHP object (true for array, false for object)
     *
     * @return object|array The deserialized PHP object
     * @throws ApiException If it fails to deserialize response body
     */
    public function parseResponseString($response, $returnType = null) {
        if (empty($response) || is_null($returnType )) {
            return null;
        }

        try {
            return ObjectSerializer::deserialize(
                $response,
                "\\TransferZero\\Model\\{$returnType}"
            );
        } catch (ApiException $e) {
            throw new ApiException(
                "[{$e->getCode()}] {$e->getMessage()}",
                $e->getCode(),
                $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
            );
        }
    }

    /**
     * Sign request using HMAC-SHA512 algorithm
     *
     * @param array $params
     * @return string
     */
    protected function signRequest($params)
    {
        $to_sign = implode('&', $params);
        return hash_hmac(
            self::DIGEST,
            $to_sign,
            $this->config->getApiSecret()
        );
    }

    /**
     * Create a hash of the body content
     *
     * @param string $body
     * @return string
     */
    protected function digestHash($body)
    {
        return openssl_digest(trim($body), self::DIGEST);
    }

    /**
     * Generate a random nonce for authorization
     *
     * @return string
     */
    protected function guidv4Nonce()
    {
        if (function_exists('com_create_guid') === true) {
            return trim(com_create_guid(), '{}');
        }
        $data = openssl_random_pseudo_bytes(16);
        $data[6] = chr(ord($data[6]) & 0x0f | 0x40); // set version to 0100
        $data[8] = chr(ord($data[8]) & 0x3f | 0x80); // set bits 6-7 to 10
        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }
}
