<?php
/**
 * OpenCorporatesSenderUpdateApi
 * PHP version 5
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BitPesa Private API
 *
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TransferZero\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use TransferZero\ApiException;
use TransferZero\Configuration;
use TransferZero\HeaderSelector;
use TransferZero\ObjectSerializer;

/**
 * OpenCorporatesSenderUpdateApi Class Doc Comment
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OpenCorporatesSenderUpdateApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

     /**
     * @var string
     */
    const DIGEST = 'SHA512';

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Use the Authorization Signature in the request headers to validate the payload
     *
     * @param $url The full url including any query strings
     * @param $body The string received through the webhook callback url
     * @param $headers The request headers received by the webhook endpoint
     *
     * @return boolean
     */
    public function validateWebhookRequest($url, $body, $headers) {
        $requestNonce = $headers["Authorization-Nonce"];
        $requestSignature = $headers["Authorization-Signature"];
        $requestkey = $headers["Authorization-Key"];

        if (empty($requestNonce) || empty($requestSignature) || ($requestkey != $this->config->getApiKey())) {
            return false;
        }

        $headerSignature = $this->signRequest([
            $requestNonce,
            'POST',
            $url,
            $this->digestHash($body)
        ]);

        return ($headerSignature == $requestSignature);
    }

    /**
     * Operation updateSender
     *
     * Update Sender with data retrieved from Open Corporates
     *
     * @param  \TransferZero\Model\OpenCorporatesSenderUpdateRequest $open_corporates_sender_update_request open_corporates_sender_update_request (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TransferZero\Model\OpenCorporatesSenderUpdateResponse|\TransferZero\Model\OpenCorporatesSenderUpdateResponse
     */
    public function updateSender($open_corporates_sender_update_request)
    {
        list($response) = $this->updateSenderWithHttpInfo($open_corporates_sender_update_request);
        return $response;
    }

    /**
     * Operation updateSenderWithHttpInfo
     *
     * Update Sender with data retrieved from Open Corporates
     *
     * @param  \TransferZero\Model\OpenCorporatesSenderUpdateRequest $open_corporates_sender_update_request (required)
     *
     * @throws \TransferZero\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TransferZero\Model\OpenCorporatesSenderUpdateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSenderWithHttpInfo($open_corporates_sender_update_request)
    {
        $returnType = '\TransferZero\Model\OpenCorporatesSenderUpdateResponse';
        $request = $this->updateSenderRequest($open_corporates_sender_update_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode == 422) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody(),
                    true
                );
            } elseif ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\OpenCorporatesSenderUpdateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody()->getContents(),
                        '\TransferZero\Model\OpenCorporatesSenderUpdateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateSenderAsync
     *
     * Update Sender with data retrieved from Open Corporates
     *
     * @param  \TransferZero\Model\OpenCorporatesSenderUpdateRequest $open_corporates_sender_update_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSenderAsync($open_corporates_sender_update_request)
    {
        return $this->updateSenderAsyncWithHttpInfo($open_corporates_sender_update_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSenderAsyncWithHttpInfo
     *
     * Update Sender with data retrieved from Open Corporates
     *
     * @param  \TransferZero\Model\OpenCorporatesSenderUpdateRequest $open_corporates_sender_update_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSenderAsyncWithHttpInfo($open_corporates_sender_update_request)
    {
        $returnType = '\TransferZero\Model\OpenCorporatesSenderUpdateResponse';
        $request = $this->updateSenderRequest($open_corporates_sender_update_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSender'
     *
     * @param  \TransferZero\Model\OpenCorporatesSenderUpdateRequest $open_corporates_sender_update_request (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateSenderRequest($open_corporates_sender_update_request)
    {
        // verify the required parameter 'open_corporates_sender_update_request' is set
        if ($open_corporates_sender_update_request === null || (is_array($open_corporates_sender_update_request) && count($open_corporates_sender_update_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $open_corporates_sender_update_request when calling updateSender'
            );
        }

        $resourcePath = '/open_corporates/update_sender';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($open_corporates_sender_update_request)) {
            $_tempBody = $open_corporates_sender_update_request;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        $query = \GuzzleHttp\Psr7\build_query($queryParams);

        $httpMethod = 'POST';
        $urlWithParams = $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : '');

        $requestNonce = $this->guidv4Nonce();
        $requestSignature = $this->signRequest([
            $requestNonce,
            strtoupper($httpMethod),
            $urlWithParams,
            $this->digestHash($httpBody)
        ]);

        $headers['Authorization-Nonce'] = $requestNonce;
        $headers['Authorization-Signature'] = $requestSignature;
        $headers['Authorization-Key'] = $this->config->getApiKey();

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        return new Request(
            'POST',
            $urlWithParams,
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        $options[RequestOptions::HTTP_ERRORS] = false;
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    /**
     * Parses and deserializes a response in string format.
     * Can be used to parse webhook responses that were already converted to strings
     *
     * @param object response the object we wish to parse
     * @param boolean returnType The type of the PHP object (true for array, false for object)
     *
     * @return object|array The deserialized PHP object
     * @throws ApiException If it fails to deserialize response body
     */
    public function parseResponseString($response, $returnType = null) {
        if (empty($response) || is_null($returnType )) {
            return null;
        }

        try {
            return ObjectSerializer::deserialize(
                $response,
                "\\TransferZero\\Model\\{$returnType}"
            );
        } catch (ApiException $e) {
            throw new ApiException(
                "[{$e->getCode()}] {$e->getMessage()}",
                $e->getCode(),
                $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
            );
        }
    }

    /**
     * Sign request using HMAC-SHA512 algorithm
     *
     * @param array $params
     * @return string
     */
    protected function signRequest($params)
    {
        $to_sign = implode('&', $params);
        return hash_hmac(
            self::DIGEST,
            $to_sign,
            $this->config->getApiSecret()
        );
    }

    /**
     * Create a hash of the body content
     *
     * @param string $body
     * @return string
     */
    protected function digestHash($body)
    {
        return openssl_digest(trim($body), self::DIGEST);
    }

    /**
     * Generate a random nonce for authorization
     *
     * @return string
     */
    protected function guidv4Nonce()
    {
        if (function_exists('com_create_guid') === true) {
            return trim(com_create_guid(), '{}');
        }
        $data = openssl_random_pseudo_bytes(16);
        $data[6] = chr(ord($data[6]) & 0x0f | 0x40); // set version to 0100
        $data[8] = chr(ord($data[8]) & 0x3f | 0x80); // set bits 6-7 to 10
        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }
}
