<?php
/**
 * PayoutMethodPixKeyTypeEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TransferZero\Model;
use \TransferZero\ObjectSerializer;

/**
 * PayoutMethodPixKeyTypeEnum Class Doc Comment
 *
 * @category Class
 * @description The type of pix key used by the recipient - &#x60;cpf&#x60;: Natural person register number - &#x60;cnpj&#x60;: Company registration number - &#x60;phone&#x60;: Phone number - &#x60;email&#x60;: Email address - &#x60;evp&#x60;: Virtual payment address
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PayoutMethodPixKeyTypeEnum
{
    /**
     * Possible values of this enum
     */
    const CPF = 'cpf';
    const CNPJ = 'cnpj';
    const PHONE = 'phone';
    const EMAIL = 'email';
    const EVP = 'evp';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CPF,
            self::CNPJ,
            self::PHONE,
            self::EMAIL,
            self::EVP,
        ];
    }
}


