<?php
/**
 * TransactionState
 *
 * PHP version 5
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TransferZero\Model;
use \TransferZero\ObjectSerializer;

/**
 * TransactionState Class Doc Comment
 *
 * @category Class
 * @description The state of the transaction, which can be one of the following:  * &#x60;initial&#x60;: Transaction is created, but not yet ready to receive payments (waiting for Sender to be KYC&#39;d and approved). * &#x60;approved&#x60;: Transaction is created and the sender is approved. Payment can be received * &#x60;pending&#x60;: Transaction has received a payin, and it&#39;s waiting for the funds to clear. * &#x60;received&#x60;: Transaction has received the correct payin amount and will start processing the payouts. * &#x60;mispaid&#x60;: Transaction received funds, but not the requested amount. The transaction will be resized, and will start payout based on the received funds. * &#x60;manual&#x60;: Some of the payments to the recipients have run into issues. Please check the recipient statuses for more information. * &#x60;paid&#x60;: Transaction has received correct payins and has performed payouts to all recipients. No further steps required * &#x60;canceled&#x60;: The transaction has been cancelled. Transactions are cancelled automatically after one hour if there was no funds received. Once transactions are funded they can be cancelled by the API user unless the recipients have been paid out. * &#x60;refunded&#x60;: The transaction has been cancelled after it has been funded, but the funds have been returned now to the sender either partially or fully. * &#x60;exception&#x60;: An exception happened during the processing of the transaction. Please contact TransferZero
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionState
{
    /**
     * Possible values of this enum
     */
    const INITIAL = 'initial';
    const APPROVED = 'approved';
    const PENDING = 'pending';
    const RECEIVED = 'received';
    const MISPAID = 'mispaid';
    const MANUAL = 'manual';
    const PAID = 'paid';
    const CANCELED = 'canceled';
    const REFUNDED = 'refunded';
    const EXCEPTION = 'exception';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INITIAL,
            self::APPROVED,
            self::PENDING,
            self::RECEIVED,
            self::MISPAID,
            self::MANUAL,
            self::PAID,
            self::CANCELED,
            self::REFUNDED,
            self::EXCEPTION,
        ];
    }
}


