<?php
/**
 * ApiLogTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TransferZero;

use PHPUnit\Framework\TestCase;

/**
 * ApiLogTest Class Doc Comment
 *
 * @category    Class
 * @description The response object returned with requests to access individual API logs
 * @package     TransferZero
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiLogTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApiLog"
     */
    public function testApiLog()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "request_method"
     */
    public function testPropertyRequestMethod()
    {
    }

    /**
     * Test attribute "request_url"
     */
    public function testPropertyRequestUrl()
    {
    }

    /**
     * Test attribute "request_body"
     */
    public function testPropertyRequestBody()
    {
    }

    /**
     * Test attribute "request_headers"
     */
    public function testPropertyRequestHeaders()
    {
    }

    /**
     * Test attribute "response_status"
     */
    public function testPropertyResponseStatus()
    {
    }

    /**
     * Test attribute "response_body"
     */
    public function testPropertyResponseBody()
    {
    }

    /**
     * Test attribute "response_headers"
     */
    public function testPropertyResponseHeaders()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }
}
