<?php
/**
 * MandateStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TransferZero;

use PHPUnit\Framework\TestCase;

/**
 * MandateStatusTest Class Doc Comment
 *
 * @category    Class
 * @description Current state of the mandate.  * &#x60;pending&#x60; — created, awaiting signing flow * &#x60;notified&#x60; — recipient has been notified to sign * &#x60;signed&#x60; — recipient signed; mandate is active * &#x60;failed&#x60; — signing flow failed (e.g. AVS/CDV rejection) * &#x60;bypassed&#x60; — administratively bypassed for an inward AZA payment
 * @package     TransferZero
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MandateStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MandateStatus"
     */
    public function testMandateStatus()
    {
    }
}
