<?php
/**
 * PayoutMethodLegalEntityTypeEnumTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TransferZero;

use PHPUnit\Framework\TestCase;

/**
 * PayoutMethodLegalEntityTypeEnumTest Class Doc Comment
 *
 * @category    Class
 * @description The entity type of the recipient.  For ZAR personal payouts valid options are: - &#x60;person&#x60;: Person  For ZAR business payouts valid options are: - &#x60;sole_proprietorship&#x60;: Sole Proprietorship - &#x60;privately_owned_company&#x60;: Privately Owned Company (Limited Company) - &#x60;publicly_owned_company&#x60;: Publicly Owned Company (PLC) - &#x60;government_owned_entity&#x60;: Government Owned Entity Trusts - &#x60;partnership&#x60;: Partnership - &#x60;go&#x60;: GO (Majority Owned Subsidiary of State-Owned Company) - &#x60;financial_institution&#x60;: Financial Institution
 * @package     TransferZero
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PayoutMethodLegalEntityTypeEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PayoutMethodLegalEntityTypeEnum"
     */
    public function testPayoutMethodLegalEntityTypeEnum()
    {
    }
}
