<?php
/**
 * PayinMethodsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TransferZero API
 *
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TransferZero;

use \TransferZero\Configuration;
use \TransferZero\ApiException;
use \TransferZero\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PayinMethodsApiTest Class Doc Comment
 *
 * @category Class
 * @package  TransferZero
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PayinMethodsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deletePayinMethod
     *
     * Deleting a payin method.
     *
     */
    public function testDeletePayinMethod()
    {
    }

    /**
     * Test case for getPayinMethod
     *
     * Fetching a payin method.
     *
     */
    public function testGetPayinMethod()
    {
    }

    /**
     * Test case for patchPayinMethod
     *
     * Updating a payin method.
     *
     */
    public function testPatchPayinMethod()
    {
    }

    /**
     * Test case for retryPayinMethod
     *
     * Retries PayinMethod.
     *
     */
    public function testRetryPayinMethod()
    {
    }
}
